cmake_minimum_required(VERSION 3.20)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
# add_compile_options(-Wall)
add_compile_options(-O3)
include_directories(${PROJECT_SOURCE_DIR}/includes)
include_directories(${PROJECT_SOURCE_DIR})
# add_executable(example1 ${PROJECT_SOURCE_DIR}/examples/example1/example1.cpp)
# add_executable(example2-train ${PROJECT_SOURCE_DIR}/examples/example2/train.cpp)
add_executable(example2-test ${PROJECT_SOURCE_DIR}/examples/example2/test.cpp)